export const LIGHT_THEME = {
  mainBground: '#fff',
  secondBground: '#F8F8F8',
  mainColor: '#000',
  smallDivShadow: '#00000005',
  menuGrey: '#5d5449',
  menuNavbarItems: '#799283',
  buttonSidebarBground: '#EBF1EF',
  buttonSidebarColor: '#135846',
  buttonGreenBground: '#135846',
  buttonGreenColor: '#fff',
  borderColor: '#f5f5f5',
  bgroundSVGMiniCard: '#FFEDEC',
  borderCardSeparator: '#EBEBEB',
};
